sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

env:
  - CYPRESS_RECORD_KEY=cefbaffc-b9a9-4504-b88a-cbddc0729b84

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  chrome: stable

script:
  - yarn run lint
  - yarn run test --singleRun --browsers Chrome,Firefox
  - yarn run integration:ci
  - yarn run build:lib 
  - yarn run semantic-release