sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

addons:
  firefox: "49.0"
  chrome: stable

script:
  - yarn run lint
  - yarn run test -- --singleRun --browsers Chrome,Firefox
  - yarn run integration